### ISSUE TITLE
Storagecraft Imagemanager, ImageManagerPoll.exe doesn't work on when applied on 32-Bit OS

### ISSUE THREAD

**Issue by chriscrisp** [N-able/CustomMonitoring#1]
The script has been incredibly usefull, however, I have run into an issue when attempting to run the ImageManagerPoll.exe.  
Upon examining the source, I found that at least part of the problem is due to the call in ImageManagerPoll/Program.cs to "C:\windows\SysWOW64\config\systemprofile\AppData\local\StorageCraft_Technology_C" on line 69 and 72.  In 32-bit Windows, these calls would be to "C:\windows\System32\config\systemprofile\AppData\local\StorageCraft_Technology_C".

Unfortunately, I have no programming experience to fix this.  But I am hoping that this will help

**Comment by chriscrisp** [comment]
Also, any references to "C:\Program Files (x86)", would have to be "C:\Program Files"

**Comment by jamesweakley** [comment]
Thanks for reporting this, and it looks like you've figured out the issue. I'll post a fix for it soon, but in the meantime you can work around the issue by symlinking the SysWOW64 folder:

C:\Windows>mklink /J SysWOW64 system32

**Comment by jamesweakley** [comment]
I've committed a fix for this issue, try downloading the new executable

**Comment by chriscrisp** [comment]
Thanks for the quick response.. I'll give it a go!
