### ISSUE TITLE
Fatal error: Unable to cast transparent proxy to type 'StorageCraft.ImageManager.Interface.IAgent5'.

### ISSUE THREAD

**Issue by alacava** [N-able/CustomMonitoring#17]
Getting the above error when running the latest ImageManager Poll

**Comment by ClintConner** [comment]
You need to make sure you are running ImageManager 7.0.5 at the very least.  I would update fully to version 7.1.0.

**Comment by ClintConner** [comment]
Did this resolve your issue?
