### ISSUE TITLE
Patch Status - PME Patch Status AMP

### ISSUE THREAD

**Issue by trevario** [N-able/CustomMonitoring#23]
in   the powershell inside the AMP:
  Name: Get-PMEServices-AMP.ps1
    Version: 0.2.0.0 (17/03/2021)
This line (line 160):
 $PMEProgramFilesFolder = "${Env:ProgramFiles(x86)}\SolarWindsMSP" is not a valid path and if I change the path variable by putting in a space in "SolarWinds MSP", it seems to work as intended and can compare versions correctly:
$PMEProgramFilesFolder = "${Env:ProgramFiles(x86)}\SolarWinds MSP"

**Comment by prejay** [comment]
Trevario; I onyl just saw your comment. Thnak You.
I notced the same thing shortly after posting, and it should have updated to 0.2.0.1 with that change shortly after the originla post.
